// <auto-generated />
using System;
using EBookDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBookDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827201335_SyncBookCoverDesignsSnapshot")]
    partial class SyncBookCoverDesignsSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuthorBillsAuthorPlans", b =>
                {
                    b.Property<int>("AuthorBillsBillId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorPlansAuthorPlanId")
                        .HasColumnType("int");

                    b.HasKey("AuthorBillsBillId", "AuthorPlansAuthorPlanId");

                    b.HasIndex("AuthorPlansAuthorPlanId");

                    b.ToTable("AuthorBillsAuthorPlans");
                });

            modelBuilder.Entity("EBookDashboard.Models.APIRawResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Chapter")
                        .HasColumnType("int");

                    b.Property<string>("ChapterNames")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsedBookId")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResponseId");

                    b.ToTable("apirawresponse");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuthorBills", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorId");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Discount");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("isActive");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(245)
                        .HasColumnType("varchar(245)")
                        .HasColumnName("PaymentReference");

                    b.Property<string>("Status")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Status");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TaxAmount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("UserEmail");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("BillId");

                    b.ToTable("authorbills");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuthorPlanFeatures", b =>
                {
                    b.Property<int>("AuthorFeaturesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuthorFeaturesId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorFeaturesId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorId");

                    b.Property<int?>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("BillId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Currency");

                    b.Property<string>("Description")
                        .HasMaxLength(245)
                        .HasColumnType("varchar(245)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpiryDate");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnName("FeatureId");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("FeatureName");

                    b.Property<decimal>("FeatureRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("FeatureRate");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("isActive");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanId");

                    b.Property<string>("Status")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<string>("UsageLimit")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("UserEmail");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("AuthorFeaturesId");

                    b.HasIndex("BillId");

                    b.HasIndex("FeatureId");

                    b.ToTable("authorplanfeatures");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuthorPlans", b =>
                {
                    b.Property<int>("AuthorPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorPlanId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("BillId");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("MaxEBooks")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PlanDays")
                        .HasColumnType("int");

                    b.Property<string>("PlanDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PlanHours")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PlanRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("TrialUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuthorPlanId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PlanId");

                    b.ToTable("authorplans");
                });

            modelBuilder.Entity("EBookDashboard.Models.Authors", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AuthorCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Compellation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AuthorId");

                    b.HasIndex("AuthorCode")
                        .IsUnique();

                    b.ToTable("authors");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookCoverDesign", b =>
                {
                    b.Property<int>("CoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CoverId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CoverId"));

                    b.Property<string>("BackImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double?>("BleedIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FrontImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double?>("FullHeightIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double?>("FullWidthIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SpineImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double?>("SpineWidthIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<double?>("TrimHeightIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double?>("TrimWidthIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WrapImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("CoverId");

                    b.HasIndex("BookId", "IsActive");

                    b.HasIndex("BookId", "UserId", "IsDeleted");

                    b.ToTable("book_cover_designs");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookCoverPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookCoverPagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("bookcoverpages");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookDesign", b =>
                {
                    b.Property<int>("DesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DesignId"));

                    b.Property<string>("DesignName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("HeightMM")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinPages")
                        .HasColumnType("int");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("WidthMM")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("DesignId");

                    b.ToTable("BookDesign");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookFormatting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InteriorStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LineSpacing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PublishingPlatform")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PublishingPlatforms")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TextSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("bookformatting");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<string>("AuthorCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BookVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("BooksBookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("bookPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PriceId");

                    b.HasIndex("BooksBookId");

                    b.ToTable("bookprice");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHtml")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBlank")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LayoutTemplate")
                        .HasColumnType("int");

                    b.Property<int>("ManuscriptVersionId")
                        .HasColumnType("int");

                    b.Property<int>("MatterType")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<int>("SectionKind")
                        .HasColumnType("int");

                    b.Property<int?>("StartPageNumber")
                        .HasColumnType("int");

                    b.Property<bool>("StartsOnRecto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("ManuscriptVersionId", "OrderIndex");

                    b.ToTable("book_sections");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookSelectionsUser", b =>
                {
                    b.Property<int>("SelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SelectionId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SelectionId");

                    b.ToTable("BookSelectionsUser");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookStateTransition", b =>
                {
                    b.Property<int>("BookStateTransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookStateTransitionId"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookStateTransitionId");

                    b.HasIndex("BookId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("bookstatetransitions");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookVersion", b =>
                {
                    b.Property<int>("BookVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookVersionId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ContentSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookVersionId");

                    b.ToTable("bookversion");
                });

            modelBuilder.Entity("EBookDashboard.Models.Books", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("AuthorCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BookContentHtml")
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dedication")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Epigraph")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ghostwriting")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("ManuscriptPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subtitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.Property<int>("isActive")
                        .HasColumnType("int")
                        .HasColumnName("isActive");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("EBookDashboard.Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("EBookDashboard.Models.ChapterIteration", b =>
                {
                    b.Property<int>("ChapterIterationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChapterIterationId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ChapterSeriesGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinalizedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("FinalizedTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("GenerationTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChapterIterationId");

                    b.HasIndex("ChapterSeriesGuid");

                    b.HasIndex("ResponseId")
                        .IsUnique();

                    b.HasIndex("UserId", "BookId", "ChapterNumber");

                    b.HasIndex("UserId", "BookId", "IsFinalized", "ChapterNumber");

                    b.ToTable("chapter_iterations");
                });

            modelBuilder.Entity("EBookDashboard.Models.Chapters", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SrNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("BookId");

                    b.ToTable("chapters");
                });

            modelBuilder.Entity("EBookDashboard.Models.CoverDesignCalculator", b =>
                {
                    b.Property<int>("CoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CoverId"));

                    b.Property<string>("BindingType")
                        .HasColumnType("longtext");

                    b.Property<string>("BookDetails")
                        .HasColumnType("longtext");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("BookVolume")
                        .HasColumnType("longtext");

                    b.Property<string>("CoverTemplate")
                        .HasColumnType("longtext");

                    b.Property<string>("CoverTemplateImagePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("InteriorType")
                        .HasColumnType("longtext");

                    b.Property<string>("MeasurementUnits")
                        .HasColumnType("longtext");

                    b.Property<string>("PageTurnDirection")
                        .HasColumnType("longtext");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<string>("PaperType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SafeArea")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SpineDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SpineTitle")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SpineWidth")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("TrimSize")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CoverId");

                    b.ToTable("coverdesigncalculator");
                });

            modelBuilder.Entity("EBookDashboard.Models.CoverProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ComputedSpineWidthIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double>("ComputedTotalHeightIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double>("ComputedTotalWidthIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<int>("CoverType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesignJson")
                        .HasColumnType("longtext");

                    b.Property<int>("PageCountUsedForSpine")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UploadedFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("cover_projects");
                });

            modelBuilder.Entity("EBookDashboard.Models.ExportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeBackMatter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludeCover")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludeFrontMatter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OutputFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("export_jobs");
                });

            modelBuilder.Entity("EBookDashboard.Models.Features", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("features");
                });

            modelBuilder.Entity("EBookDashboard.Models.FinalizeChapters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorCode")
                        .HasColumnType("longtext");

                    b.Property<string>("BookCode")
                        .HasColumnType("longtext");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Chapter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("finalizechapters");
                });

            modelBuilder.Entity("EBookDashboard.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasMaxLength(100)
                        .HasColumnType("tinyint(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("LanguageId");

                    b.ToTable("language");
                });

            modelBuilder.Entity("EBookDashboard.Models.LayoutProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BleedMode")
                        .HasColumnType("int");

                    b.Property<string>("BodyFontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("BodyFontSizePt")
                        .HasColumnType("double");

                    b.Property<bool>("ChaptersStartOnRecto")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("FirstLineIndentIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<string>("H1FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("H1FontSizePt")
                        .HasColumnType("double");

                    b.Property<string>("H2FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("H2FontSizePt")
                        .HasColumnType("double");

                    b.Property<double>("HeaderFooterFontSizePt")
                        .HasColumnType("double");

                    b.Property<bool>("IsEbookProfile")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("LineSpacing")
                        .HasColumnType("double");

                    b.Property<double>("MarginBottomIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double>("MarginInsideIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double>("MarginOutsideIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double>("MarginTopIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<bool>("MarginsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NoIndentOnFirstPara")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PageNumberPosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("ParagraphSpacingAfterPt")
                        .HasColumnType("double");

                    b.Property<double>("ParagraphSpacingBeforePt")
                        .HasColumnType("double");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowPageNumbers")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TextAlignment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("TocFontSizePt")
                        .HasColumnType("double");

                    b.Property<bool>("UseRecommendedMargins")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IsEbookProfile")
                        .IsUnique();

                    b.ToTable("layout_profiles");
                });

            modelBuilder.Entity("EBookDashboard.Models.ManuscriptVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ParsedStructureJson")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SourceFormat")
                        .HasColumnType("int");

                    b.Property<string>("StoredFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IsActive");

                    b.HasIndex("ProjectId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("manuscript_versions");
                });

            modelBuilder.Entity("EBookDashboard.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("EBookDashboard.Models.ParsedBookContent", b =>
                {
                    b.Property<int>("ParsedContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParsedContentId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("BookSectionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterName")
                        .HasMaxLength(245)
                        .HasColumnType("varchar(245)")
                        .HasColumnName("chapter_name");

                    b.Property<string>("ChapterTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullParsedDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightChapterName")
                        .HasColumnType("longtext");

                    b.Property<string>("HighlightOfPreviousChapter")
                        .HasColumnType("longtext")
                        .HasColumnName("highlight_of_previous_chapter");

                    b.Property<string>("HighlightsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserInput")
                        .HasColumnType("longtext")
                        .HasColumnName("user_input");

                    b.HasKey("ParsedContentId");

                    b.ToTable("parsedbookcontent");
                });

            modelBuilder.Entity("EBookDashboard.Models.PasswordReset", b =>
                {
                    b.Property<int>("ResetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ResetId");

                    b.HasIndex("Email", "OTP", "IsUsed");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("EBookDashboard.Models.PlanFeatures", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeatureId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Currency")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Currency");

                    b.Property<string>("Description")
                        .HasMaxLength(245)
                        .HasColumnType("varchar(245)")
                        .HasColumnName("Description");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("FeatureName");

                    b.Property<decimal>("FeatureRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("FeatureRate");

                    b.Property<string>("FeatureType")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("FeatureType");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsUnlimited");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanId");

                    b.Property<string>("Status")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Status");

                    b.Property<string>("UsageLimit")
                        .HasMaxLength(245)
                        .HasColumnType("varchar(245)")
                        .HasColumnName("UsageLimit");

                    b.HasKey("FeatureId");

                    b.ToTable("planfeatures");
                });

            modelBuilder.Entity("EBookDashboard.Models.Plans", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<bool>("AllowAnalytics")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowDownloads")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowFullDashboard")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowPublishing")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateddAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("MaxChapters")
                        .HasColumnType("int");

                    b.Property<int>("MaxEBooks")
                        .HasColumnType("int");

                    b.Property<int>("MaxPages")
                        .HasColumnType("int");

                    b.Property<int>("PlanDays")
                        .HasColumnType("int");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanHours")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PlanRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            AllowAnalytics = false,
                            AllowDownloads = false,
                            AllowFullDashboard = false,
                            AllowPublishing = false,
                            CreateddAt = new DateTime(2026, 7, 27, 18, 8, 4, 658, DateTimeKind.Utc).AddTicks(9162),
                            Currency = "usd",
                            IsActive = 1,
                            MaxChapters = 0,
                            MaxEBooks = 0,
                            MaxPages = 0,
                            PlanDays = 30,
                            PlanDescription = "Free 1-month trial",
                            PlanHours = 0,
                            PlanName = "Free Trial",
                            PlanRate = 0m
                        },
                        new
                        {
                            PlanId = 2,
                            AllowAnalytics = false,
                            AllowDownloads = false,
                            AllowFullDashboard = false,
                            AllowPublishing = false,
                            CreateddAt = new DateTime(2026, 7, 27, 18, 8, 4, 658, DateTimeKind.Utc).AddTicks(9171),
                            Currency = "usd",
                            IsActive = 1,
                            MaxChapters = 0,
                            MaxEBooks = 0,
                            MaxPages = 0,
                            PlanDays = 30,
                            PlanDescription = "Basic monthly subscription",
                            PlanHours = 0,
                            PlanName = "Basic Plan",
                            PlanRate = 9.99m
                        },
                        new
                        {
                            PlanId = 3,
                            AllowAnalytics = false,
                            AllowDownloads = false,
                            AllowFullDashboard = false,
                            AllowPublishing = false,
                            CreateddAt = new DateTime(2026, 7, 27, 18, 8, 4, 658, DateTimeKind.Utc).AddTicks(9176),
                            Currency = "usd",
                            IsActive = 1,
                            MaxChapters = 0,
                            MaxEBooks = 0,
                            MaxPages = 0,
                            PlanDays = 365,
                            PlanDescription = "Yearly subscription",
                            PlanHours = 0,
                            PlanName = "Pro Plan",
                            PlanRate = 99.99m
                        });
                });

            modelBuilder.Entity("EBookDashboard.Models.PricingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("FreeAllowance")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PricingRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "USD",
                            DisplayName = "AI writing",
                            FreeAllowance = 20,
                            IsActive = true,
                            Key = "writing.per_page",
                            Unit = 0,
                            UnitAmount = 0.50m,
                            UpdatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            DisplayName = "Custom image cover",
                            FreeAllowance = 0,
                            IsActive = true,
                            Key = "cover.custom_image",
                            Unit = 1,
                            UnitAmount = 10.00m,
                            UpdatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Currency = "USD",
                            DisplayName = "Premium formatting",
                            FreeAllowance = 0,
                            IsActive = true,
                            Key = "formatting.premium",
                            Unit = 1,
                            UnitAmount = 3.00m,
                            UpdatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Currency = "USD",
                            DisplayName = "Paperback package",
                            FreeAllowance = 0,
                            IsActive = true,
                            Key = "export.paperback",
                            Unit = 2,
                            UnitAmount = 20.00m,
                            UpdatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Currency = "USD",
                            DisplayName = "Hardcover package",
                            FreeAllowance = 0,
                            IsActive = true,
                            Key = "export.hardcover",
                            Unit = 2,
                            UnitAmount = 30.00m,
                            UpdatedAtUtc = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EBookDashboard.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasBleed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCustomTrim")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PaperType")
                        .HasColumnType("int");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<double>("TrimHeightIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<double>("TrimWidthIn")
                        .HasPrecision(10, 4)
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EBookDashboard.Models.PubCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CostId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("AuthorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("CostId");

                    b.ToTable("PubCosts");
                });

            modelBuilder.Entity("EBookDashboard.Models.RecordStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("RecordStatus");
                });

            modelBuilder.Entity("EBookDashboard.Models.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("AllowAnalytics")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowDownloads")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowFullDashboard")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowPublishing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            AllowAnalytics = true,
                            AllowDelete = true,
                            AllowDownloads = true,
                            AllowEdit = true,
                            AllowFullDashboard = true,
                            AllowPublishing = true,
                            Description = "Administrator with full access",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            AllowAnalytics = true,
                            AllowDelete = true,
                            AllowDownloads = true,
                            AllowEdit = true,
                            AllowFullDashboard = true,
                            AllowPublishing = true,
                            Description = "Author with publishing access",
                            RoleName = "Author"
                        },
                        new
                        {
                            RoleId = 3,
                            AllowAnalytics = false,
                            AllowDelete = false,
                            AllowDownloads = false,
                            AllowEdit = false,
                            AllowFullDashboard = false,
                            AllowPublishing = false,
                            Description = "Reader with limited access",
                            RoleName = "Reader"
                        });
                });

            modelBuilder.Entity("EBookDashboard.Models.Settings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("SettingId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EBookDashboard.Models.UserFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AuthorPlanId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorPlanId");

                    b.HasIndex("FeatureId");

                    b.ToTable("UserFeatures");
                });

            modelBuilder.Entity("EBookDashboard.Models.UserPreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("PreferenceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("EBookDashboard.Models.UserStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("DayStreak")
                        .HasColumnType("int");

                    b.Property<int>("HoursRead")
                        .HasColumnType("int");

                    b.Property<int>("PagesRead")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("userstats");
                });

            modelBuilder.Entity("EBookDashboard.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AuthorCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("HasCompletedTour")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecretQuestion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecretQuestionAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EBookDashboard.Models.ViewModels.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("AuthorBillsAuthorPlans", b =>
                {
                    b.HasOne("EBookDashboard.Models.AuthorBills", null)
                        .WithMany()
                        .HasForeignKey("AuthorBillsBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBookDashboard.Models.AuthorPlans", null)
                        .WithMany()
                        .HasForeignKey("AuthorPlansAuthorPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBookDashboard.Models.AuditLog", b =>
                {
                    b.HasOne("EBookDashboard.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuthorPlanFeatures", b =>
                {
                    b.HasOne("EBookDashboard.Models.AuthorBills", "AuthorBill")
                        .WithMany("AuthorPlanFeatures")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EBookDashboard.Models.PlanFeatures", "PlanFeature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AuthorBill");

                    b.Navigation("PlanFeature");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuthorPlans", b =>
                {
                    b.HasOne("EBookDashboard.Models.Authors", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBookDashboard.Models.Plans", "Plan")
                        .WithMany("AuthorPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookPrice", b =>
                {
                    b.HasOne("EBookDashboard.Models.Books", null)
                        .WithMany("BookPrice")
                        .HasForeignKey("BooksBookId");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookSection", b =>
                {
                    b.HasOne("EBookDashboard.Models.ManuscriptVersion", "ManuscriptVersion")
                        .WithMany("Sections")
                        .HasForeignKey("ManuscriptVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBookDashboard.Models.BookSection", "ParentSection")
                        .WithMany("ChildSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManuscriptVersion");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("EBookDashboard.Models.Books", b =>
                {
                    b.HasOne("EBookDashboard.Models.Authors", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBookDashboard.Models.Chapters", b =>
                {
                    b.HasOne("EBookDashboard.Models.Books", null)
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBookDashboard.Models.CoverProject", b =>
                {
                    b.HasOne("EBookDashboard.Models.Project", "Project")
                        .WithMany("CoverProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EBookDashboard.Models.ExportJob", b =>
                {
                    b.HasOne("EBookDashboard.Models.Project", "Project")
                        .WithMany("ExportJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EBookDashboard.Models.LayoutProfile", b =>
                {
                    b.HasOne("EBookDashboard.Models.Project", "Project")
                        .WithMany("LayoutProfiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EBookDashboard.Models.ManuscriptVersion", b =>
                {
                    b.HasOne("EBookDashboard.Models.Project", "Project")
                        .WithMany("ManuscriptVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EBookDashboard.Models.Notification", b =>
                {
                    b.HasOne("EBookDashboard.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBookDashboard.Models.UserFeatures", b =>
                {
                    b.HasOne("EBookDashboard.Models.AuthorPlans", "AuthorPlan")
                        .WithMany()
                        .HasForeignKey("AuthorPlanId");

                    b.HasOne("EBookDashboard.Models.Features", "Feature")
                        .WithMany("UserFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorPlan");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("EBookDashboard.Models.UserPreference", b =>
                {
                    b.HasOne("EBookDashboard.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBookDashboard.Models.UserStats", b =>
                {
                    b.HasOne("EBookDashboard.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBookDashboard.Models.Users", b =>
                {
                    b.HasOne("EBookDashboard.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EBookDashboard.Models.AuthorBills", b =>
                {
                    b.Navigation("AuthorPlanFeatures");
                });

            modelBuilder.Entity("EBookDashboard.Models.Authors", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EBookDashboard.Models.BookSection", b =>
                {
                    b.Navigation("ChildSections");
                });

            modelBuilder.Entity("EBookDashboard.Models.Books", b =>
                {
                    b.Navigation("BookPrice");

                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("EBookDashboard.Models.Features", b =>
                {
                    b.Navigation("UserFeatures");
                });

            modelBuilder.Entity("EBookDashboard.Models.ManuscriptVersion", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EBookDashboard.Models.Plans", b =>
                {
                    b.Navigation("AuthorPlans");
                });

            modelBuilder.Entity("EBookDashboard.Models.Project", b =>
                {
                    b.Navigation("CoverProjects");

                    b.Navigation("ExportJobs");

                    b.Navigation("LayoutProfiles");

                    b.Navigation("ManuscriptVersions");
                });

            modelBuilder.Entity("EBookDashboard.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
